<a href="https://colab.research.google.com/github/Crisosth/IA/blob/main/RNA_Regress%C3%A3o_CarrosUsados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import io

In [ ]:
# carregando a base de dados com ISO-8859 - devido aos strings existentes
base = pd.read_csv('autos.csv', encoding = 'ISO-8859-1')

In [ ]:
# deletando as colunas não importantes
# axis = 1 - deletar a coluna inteira
base = base.drop('dateCrawled', axis = 1)
base = base.drop('seller', axis = 1)
base = base.drop('dateCreated', axis = 1)
base = base.drop('nrOfPictures', axis = 1)
base = base.drop('postalCode', axis = 1)
base = base.drop('lastSeen', axis = 1)

In [ ]:
# analisando outras colunas
# mostra os valores da coluna e as quantidades
base['offerType'].value_counts()

offerType
Angebot    371516
Gesuch         12
Name: count, dtype: int64

In [ ]:
# deletando a coluna offerType
base = base.drop('offerType', axis = 1)

In [ ]:
# analisando outras colunas
# mostra os valores da coluna e as quantidades
base['name'].value_counts()

name
Ford_Fiesta                                              657
BMW_318i                                                 627
Opel_Corsa                                               622
Volkswagen_Golf_1.4                                      603
BMW_316i                                                 523
                                                        ...
Audi_A4_Avant_Klima_Gruene_Plakette_TÜV_&AU_NEU_XENON      1
Renault_clio_in_gold_450VB_!!                              1
Fiat_Doblo_1.6_Multijet                                    1
Renault_Laguna_1                                           1
BMW_M135i_vollausgestattet_NP_52.720____Euro               1
Name: count, Length: 233531, dtype: int64

In [ ]:
# deletando coluna name
base = base.drop('name', axis = 1)

In [ ]:
# localizando registros que atendem uma condição
# condição - preço <= 10 euros
inl = base.loc[base.price <= 10]
inl

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
7,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein
40,0,test,NaN,1990,NaN,0,corsa,150000,1,benzin,opel,NaN
60,1,control,suv,1994,manuell,286,NaN,150000,11,NaN,sonstige_autos,NaN
91,1,control,limousine,1995,manuell,113,e_klasse,150000,4,diesel,mercedes_benz,nein
115,0,test,NaN,2017,manuell,0,golf,5000,12,benzin,volkswagen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371356,0,control,NaN,2000,manuell,65,corsa,150000,0,NaN,opel,ja
371392,0,test,kleinwagen,2002,manuell,60,fiesta,150000,3,benzin,ford,NaN
371402,0,control,kleinwagen,1999,manuell,53,swift,150000,3,benzin,suzuki,NaN
371431,0,control,kleinwagen,1999,manuell,37,arosa,150000,7,benzin,seat,ja
371522,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja

In [ ]:
# eliminando valores <= 10 da coluna price
base = base[base.price > 10]

In [ ]:
# localizando registros que atendem uma condição
# condição - preço > 350.000 Euros
in2 = base.loc[base.price > 350000]
in2

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1846,579000,control,coupe,1980,manuell,277,andere,20000,12,benzin,bmw,nein
10649,420000,control,coupe,2004,manuell,483,911,50000,4,benzin,porsche,nein
14663,11111111,control,coupe,2003,manuell,64,polo,150000,2,benzin,volkswagen,NaN
16889,1000000,control,kombi,1998,NaN,0,mondeo,150000,0,benzin,ford,ja
20143,1250000,test,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
364171,3890000,test,coupe,2006,NaN,799,NaN,5000,7,NaN,sonstige_autos,nein
365461,599000,control,coupe,1980,manuell,377,andere,5000,3,benzin,bmw,nein
366653,99999999,control,cabrio,1996,manuell,192,3er,150000,0,NaN,bmw,NaN
366861,3895000,test,coupe,2006,NaN,799,NaN,5000,4,benzin,sonstige_autos,nein
367041,1600000,test,coupe,2005,NaN,625,NaN,10000,4,benzin,sonstige_autos,nein

In [ ]:
# eliminando valores > 350.000 da coluna price
base = base[base.price < 350000]

In [ ]:
# verificando valores nulos no tipo do veiculo
base.loc[pd.isnull(base['vehicleType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
22,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
31,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [ ]:
# encontrando valor que mais se repete em vehicleType
base['vehicleType'].value_counts()

vehicleType
limousine     93614
kleinwagen    78014
kombi         65921
bus           29699
cabrio        22509
coupe         18386
suv           14477
andere         3125
Name: count, dtype: int64

In [ ]:
# verificando valores nulos no campo gearbox
base.loc[pd.isnull(base['gearbox'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
15,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
32,245,test,limousine,1994,NaN,0,golf,150000,2,benzin,volkswagen,nein
37,1500,test,NaN,2016,NaN,0,kangoo,150000,1,diesel,renault,nein
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371443,3300,control,kombi,2006,NaN,0,touran,150000,7,diesel,volkswagen,NaN
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [ ]:
# encontrando valor que mais se repete em gearbox
base['gearbox'].value_counts()

gearbox
manuell      266547
automatik     75508
Name: count, dtype: int64

In [ ]:
# verificando valores nulos no campo modelo
base.loc[pd.isnull(base['model'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
83,350,control,kleinwagen,1997,manuell,54,NaN,150000,3,NaN,fiat,ja
139,1450,control,limousine,1992,manuell,136,NaN,150000,0,NaN,audi,nein
156,6799,control,kleinwagen,2009,NaN,60,NaN,20000,5,benzin,volkswagen,nein
165,500,control,kleinwagen,1999,manuell,0,NaN,150000,0,benzin,renault,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371399,560,control,kleinwagen,2001,automatik,170,NaN,90000,0,benzin,fiat,ja
371476,9400,control,kombi,2007,manuell,200,NaN,150000,4,diesel,sonstige_autos,ja
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [ ]:
# encontrando valor que mais se repete em model
base['model'].value_counts()

model
golf               28989
andere             25560
3er                19905
polo               12604
corsa              12149
                   ...
serie_2                8
rangerover             6
serie_3                3
serie_1                1
discovery_sport        1
Name: count, Length: 251, dtype: int64

In [ ]:
# verificando valores nulos no campo tipo de combustivel
base.loc[pd.isnull(base['fuelType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
13,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
36,1600,control,andere,1991,manuell,75,kadett,70000,0,NaN,opel,NaN
41,7500,control,limousine,2002,automatik,306,e_klasse,150000,4,NaN,mercedes_benz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371496,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [ ]:
# encontrando valor que mais se repete em tipo de combustivel
base['fuelType'].value_counts()

fuelType
benzin     217582
diesel     106002
lpg          5222
cng           557
hybrid        271
andere        165
elektro       101
Name: count, dtype: int64

In [ ]:
# verificando valores nulos no campo reparo
base.loc[pd.isnull(base['notRepairedDamage'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
8,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
12,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371507,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN
371514,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN
371515,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN

In [ ]:
# encontrando valor que mais se repete em reparo
base['notRepairedDamage'].value_counts()

notRepairedDamage
nein    259301
ja       34004
Name: count, dtype: int64

In [ ]:
# corrigindo valores faltantes
# criando variavel com as associações dos campos/valores
valores = {'vehicleType': 'limousine',
           'gearbox': 'manuell',
           'model': 'golf',
           'fuelType': 'benzin',
           'notRepairedDamage': 'nein'}

In [ ]:
# fazendo as correções
base = base.fillna(value = valores)

In [ ]:
#separando a base dos atributos previsores
# iloc [intervalo de linhas (0 :f+1), intervalo de colunas(0: f+1)]
previsores = base.iloc[:, 1:12] .values

In [ ]:
previsores[0]

array(['test', 'limousine', 1993, 'manuell', 0, 'golf', 150000, 0,
       'benzin', 'volkswagen', 'nein'], dtype=object)

In [ ]:
# separando a base do atributo objetivo
preco_real = base.iloc[:, 0].values

In [ ]:
preco_real

array([  480, 18300,  9800, ...,  9200,  3400, 28990])

In [ ]:
# transformando valores categoricos em valores numericos
# importando a biblioteca LabelEncoder
from sklearn.preprocessing import LabelEncoder

In [ ]:
# criando o objeto da classe Label Encoder
labelencoder_previsores = LabelEncoder()

In [ ]:
# transformando o atributo abtest (coluna 0) em valores numericos
previsores[:, 0] = labelencoder_previsores.fit_transform(previsores[:, 0])

In [ ]:
# transformando os outros atributos (coluna 1, 2 , 3 , 4, 5, 8, 9 , 10) em valores numericos
previsores[:, 1] = labelencoder_previsores.fit_transform(previsores[:, 1])
previsores[:, 3] = labelencoder_previsores.fit_transform(previsores[:, 3])
previsores[:, 5] = labelencoder_previsores.fit_transform(previsores[:, 5])
previsores[:, 8] = labelencoder_previsores.fit_transform(previsores[:, 8])
previsores[:, 9] = labelencoder_previsores.fit_transform(previsores[:, 9])
previsores[:, 10] = labelencoder_previsores.fit_transform(previsores[:, 10])

In [ ]:
previsores[0:20]

array([[1, 6, 1993, 1, 0, 118, 150000, 0, 1, 38, 1],
       [1, 3, 2011, 1, 190, 118, 125000, 5, 3, 1, 0],
       [1, 7, 2004, 0, 163, 119, 125000, 8, 3, 14, 1],
       [1, 4, 2001, 1, 75, 118, 150000, 6, 1, 38, 1],
       [1, 4, 2008, 1, 69, 103, 90000, 7, 3, 31, 1],
       [1, 6, 1995, 1, 102, 11, 150000, 10, 1, 2, 0],
       [1, 2, 2004, 1, 109, 8, 150000, 8, 1, 25, 1],
       [0, 1, 2014, 1, 125, 61, 30000, 8, 1, 10, 1],
       [1, 4, 1998, 1, 101, 118, 150000, 0, 1, 38, 1],
       [0, 6, 2004, 1, 105, 10, 150000, 12, 1, 19, 1],
       [0, 5, 2005, 1, 140, 171, 150000, 12, 3, 38, 0],
       [0, 5, 1995, 1, 115, 171, 150000, 11, 1, 38, 1],
       [0, 5, 2004, 1, 131, 171, 150000, 2, 1, 38, 1],
       [0, 7, 2011, 1, 190, 161, 70000, 3, 3, 23, 1],
       [1, 4, 1910, 1, 0, 130, 5000, 0, 1, 10, 1],
       [1, 6, 2016, 1, 60, 174, 150000, 0, 1, 38, 1],
       [0, 4, 2004, 0, 75, 228, 150000, 2, 1, 27, 1],
       [1, 1, 2007, 1, 136, 61, 150000, 6, 3, 10, 1],
       [1, 1, 2004, 1, 102, 33, 150000, 1, 1, 20, 1],
       [0, 3, 2009, 1, 160, 200, 100000, 4, 1, 38, 1]], dtype=object)

In [ ]:
# detalhando os valores convertidos oelo LabelEncoder
# importando a biblioteca OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
# criando o onjeto da classe One Hot Encoder
# detalhando os valores categoricos das colunas convertidas
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0, 1, 3, 5, 8, 9, 10])], remainder='passthrough')

In [ ]:
# atualizando a base de dados previsores
previsores = columnTransformer.fit_transform(previsores).toarray()

In [ ]:
# mostrando numero de linhas
len(previsores)

359291

In [ ]:
# mostrando numero de colunas
len(previsores[0])

316

In [ ]:
previsores

array([[0.00e+00, 1.00e+00, 0.00e+00, ..., 0.00e+00, 1.50e+05, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.90e+02, 1.25e+05, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.63e+02, 1.25e+05, 8.00e+00],
       ...,
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.02e+02, 1.50e+05, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e+02, 1.50e+05, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 3.20e+02, 5.00e+04, 8.00e+00]])

In [ ]:
# importando bibliotecas
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# criando a RNA regressor
regressor = Sequential()

In [ ]:
# criando a primeira camada oculta e a camada de entrada
# numero de neuronios camada oculta = (316 + 1) / 2 = 158.5
# numero de neuronios camada entrada = 316
regressor.add(Dense(units = 158, activation = 'relu', input_dim = 316))

# criando mais uma camada oculta
regressor.add(Dense(units = 158, activation = 'relu'))

# criando a camada de saida
# função de ativação linear para previsão de números
regressor.add(Dense(units = 1, activation = 'linear'))

In [ ]:
# compilação da RNA
# funções loss e metrics especificas para regressão - mean_absolute_error
regressor.compile(loss = 'mean_absolute_error', optimizer = 'adam', metrics = ['mean_absolute_error'])

In [ ]:
# treinamento da RNA
# atualização de pesos a cada 300 registros
# repetir 100 vezes
regressor.fit(previsores, preco_real, batch_size = 300, epochs = 100)

Epoch 1/100
1198/1198 [==============================] - 9s 7ms/step - loss: 3844.5222 - mean_absolute_error: 3844.5222
Epoch 2/100
1198/1198 [==============================] - 11s 9ms/step - loss: 3292.8979 - mean_absolute_error: 3292.8979
Epoch 3/100
1198/1198 [==============================] - 8s 6ms/step - loss: 3027.0342 - mean_absolute_error: 3027.0342
Epoch 4/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2869.4302 - mean_absolute_error: 2869.4304
Epoch 5/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2797.4485 - mean_absolute_error: 2797.4485
Epoch 6/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2738.7544 - mean_absolute_error: 2738.7544
Epoch 7/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2698.9575 - mean_absolute_error: 2698.9575
Epoch 8/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2646.7864 - mean_absolute_error: 2646.7864
Epoch 9/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2605.1304 - mean_absolute_error: 2605.1304
Epoch 10/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2559.6724 - mean_absolute_error: 2559.6724
Epoch 11/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2531.4561 - mean_absolute_error: 2531.4558
Epoch 12/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2502.8914 - mean_absolute_error: 2502.8914
Epoch 13/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2481.3354 - mean_absolute_error: 2481.3354
Epoch 14/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2450.3689 - mean_absolute_error: 2450.3694
Epoch 15/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2451.5789 - mean_absolute_error: 2451.5789
Epoch 16/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2451.6213 - mean_absolute_error: 2451.6213
Epoch 17/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2431.9219 - mean_absolute_error: 2431.9219
Epoch 18/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2432.8125 - mean_absolute_error: 2432.8125
Epoch 19/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2428.9263 - mean_absolute_error: 2428.9263
Epoch 20/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2417.7959 - mean_absolute_error: 2417.7959
Epoch 21/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2417.2883 - mean_absolute_error: 2417.2883
Epoch 22/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2405.6045 - mean_absolute_error: 2405.6045
Epoch 23/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2409.0229 - mean_absolute_error: 2409.0229
Epoch 24/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2379.9351 - mean_absolute_error: 2379.9351
Epoch 25/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2378.1577 - mean_absolute_error: 2378.1577
Epoch 26/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2373.5071 - mean_absolute_error: 2373.5071
Epoch 27/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2381.3289 - mean_absolute_error: 2381.3289
Epoch 28/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2376.5693 - mean_absolute_error: 2376.5693
Epoch 29/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2358.2371 - mean_absolute_error: 2358.2371
Epoch 30/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2358.1963 - mean_absolute_error: 2358.1963
Epoch 31/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2347.6262 - mean_absolute_error: 2347.6262
Epoch 32/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2359.7354 - mean_absolute_error: 2359.7354
Epoch 33/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2357.1211 - mean_absolute_error: 2357.1211
Epoch 34/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2356.9600 - mean_absolute_error: 2356.9600
Epoch 35/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2345.7100 - mean_absolute_error: 2345.7100
Epoch 36/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2350.1606 - mean_absolute_error: 2350.1606
Epoch 37/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2332.3196 - mean_absolute_error: 2332.3196
Epoch 38/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2329.9124 - mean_absolute_error: 2329.9124
Epoch 39/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2332.5137 - mean_absolute_error: 2332.5137
Epoch 40/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2320.7771 - mean_absolute_error: 2320.7771
Epoch 41/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2311.5427 - mean_absolute_error: 2311.5427
Epoch 42/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2327.8633 - mean_absolute_error: 2327.8633
Epoch 43/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2314.3796 - mean_absolute_error: 2314.3796
Epoch 44/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2311.2808 - mean_absolute_error: 2311.2808
Epoch 45/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2309.8435 - mean_absolute_error: 2309.8435
Epoch 46/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2309.0320 - mean_absolute_error: 2309.0320
Epoch 47/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2303.2375 - mean_absolute_error: 2303.2375
Epoch 48/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2305.6875 - mean_absolute_error: 2305.6875
Epoch 49/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2306.3984 - mean_absolute_error: 2306.3984
Epoch 50/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2310.9844 - mean_absolute_error: 2310.9846
Epoch 51/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2310.8169 - mean_absolute_error: 2310.8169
Epoch 52/100
1198/1198 [==============================] - 11s 10ms/step - loss: 2282.1248 - mean_absolute_error: 2282.1248
Epoch 53/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2301.0554 - mean_absolute_error: 2301.0554
Epoch 54/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2311.6851 - mean_absolute_error: 2311.6851
Epoch 55/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2295.2307 - mean_absolute_error: 2295.2307
Epoch 56/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2285.1252 - mean_absolute_error: 2285.1252
Epoch 57/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2280.6294 - mean_absolute_error: 2280.6294
Epoch 58/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2277.5002 - mean_absolute_error: 2277.5002
Epoch 59/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2290.5181 - mean_absolute_error: 2290.5181
Epoch 60/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2280.4424 - mean_absolute_error: 2280.4424
Epoch 61/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2293.2100 - mean_absolute_error: 2293.2100
Epoch 62/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2278.9548 - mean_absolute_error: 2278.9551
Epoch 63/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2280.8994 - mean_absolute_error: 2280.8994
Epoch 64/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2280.9897 - mean_absolute_error: 2280.9897
Epoch 65/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2265.5491 - mean_absolute_error: 2265.5491
Epoch 66/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2270.4126 - mean_absolute_error: 2270.4126
Epoch 67/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2262.1218 - mean_absolute_error: 2262.1218
Epoch 68/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2280.0535 - mean_absolute_error: 2280.0535
Epoch 69/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2269.6204 - mean_absolute_error: 2269.6204
Epoch 70/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2263.3762 - mean_absolute_error: 2263.3762
Epoch 71/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2267.7825 - mean_absolute_error: 2267.7825
Epoch 72/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2251.0605 - mean_absolute_error: 2251.0605
Epoch 73/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2260.8257 - mean_absolute_error: 2260.8257
Epoch 74/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2253.5564 - mean_absolute_error: 2253.5564
Epoch 75/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2252.2092 - mean_absolute_error: 2252.2092
Epoch 76/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2251.2288 - mean_absolute_error: 2251.2288
Epoch 77/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2258.0435 - mean_absolute_error: 2258.0435
Epoch 78/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2247.9175 - mean_absolute_error: 2247.9175
Epoch 79/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2259.3911 - mean_absolute_error: 2259.3911
Epoch 80/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2248.2043 - mean_absolute_error: 2248.2043
Epoch 81/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2245.9783 - mean_absolute_error: 2245.9780
Epoch 82/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2239.1726 - mean_absolute_error: 2239.1726
Epoch 83/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2252.4971 - mean_absolute_error: 2252.4971
Epoch 84/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2250.1533 - mean_absolute_error: 2250.1533
Epoch 85/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2244.5000 - mean_absolute_error: 2244.5000
Epoch 86/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2243.3884 - mean_absolute_error: 2243.3884
Epoch 87/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2237.8833 - mean_absolute_error: 2237.8833
Epoch 88/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2227.4695 - mean_absolute_error: 2227.4695
Epoch 89/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2238.3213 - mean_absolute_error: 2238.3213
Epoch 90/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2235.3149 - mean_absolute_error: 2235.3149
Epoch 91/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2239.9529 - mean_absolute_error: 2239.9529
Epoch 92/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2238.8052 - mean_absolute_error: 2238.8052
Epoch 93/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2231.4761 - mean_absolute_error: 2231.4761
Epoch 94/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2224.7615 - mean_absolute_error: 2224.7615
Epoch 95/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2228.3267 - mean_absolute_error: 2228.3269
Epoch 96/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2230.3569 - mean_absolute_error: 2230.3569
Epoch 97/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2233.0005 - mean_absolute_error: 2233.0005
Epoch 98/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2223.1863 - mean_absolute_error: 2223.1863
Epoch 99/100
1198/1198 [==============================] - 7s 6ms/step - loss: 2221.3965 - mean_absolute_error: 2221.3965
Epoch 100/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2216.8633 - mean_absolute_error: 2216.8633

In [ ]:
# fazendo as previsões dos preços dos carros
# vai ler cada um dos 359291 registros da base de dados previsores
# passar na RNA com os últimos pesos calculados
# e vai prever novos preços dos carros
previsoes = regressor.predict(previsores)

11228/11228 [==============================] - 23s 2ms/step

In [ ]:
# verificando as medias dos preços previstos
prev = previsoes.mean()

In [ ]:
# verificando as medias dos preços existentes
real = preco_real.mean()

In [ ]:
# avaliando a precisao da RNA - comparar previsoes e preco_real
prec = (prev * 100) / real

In [ ]:
# mostrando a precisao
prec

95.53456518126242